apiVersion: v1
kind: Pod
metadata:
  name: couchbase-pod
  labels:
    name: couchbase-pod
spec:
  containers:
  - name: couchbase
    image: somkiat/couchbase:latest
    ports:
    - containerPort: 8091
    volumeMounts:
    - mountPath: /var/couchbase/lib
      name: couchbase-data
  volumes:
  - name: couchbase-data
    hostPath:
      path: /opt/data
