apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.8
        ports:
        - containerPort: 80
        volumeMounts:
            - name: try-nfs
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: try-nfs
        persistentVolumeClaim:
          claimName: pvc-nfs
