apiVersion: v1
kind: Service
metadata:
  name: nginx-web
  labels:
    name: nginx-web
    environment: development
spec:
  selector:
    name: nginx
  type: NodePort
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
     nodePort: 32500
